In [2]:
from sklearn.model_selection import TimeSeriesSplit
import numpy as np


TimeSeriesSplit(max_train_size=None, n_splits=3)
TRAIN: [0] TEST: [1]
TRAIN: [0 1] TEST: [2]
TRAIN: [0 1 2] TEST: [3]


In [12]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])
tscv = TimeSeriesSplit(n_splits=2)
print(tscv)  



TimeSeriesSplit(max_train_size=None, n_splits=2)


In [13]:
for train_index, test_index in tscv.split(X):
   print("TRAIN:", train_index, "TEST:", test_index)
   
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]
   print("X_train : ",X_train)

TRAIN: [0 1] TEST: [2]
X_train :  [[1 2]
 [3 4]]
TRAIN: [0 1 2] TEST: [3]
X_train :  [[1 2]
 [3 4]
 [1 2]]


In [14]:
X_train

array([[1, 2],
       [3, 4],
       [1, 2]])

In [15]:
X_test

array([[3, 4]])

In [16]:
y_train

array([1, 2, 3])

In [17]:
y_test

array([4])

In [20]:
li = [1,2,3,4]
sum(li)/len(li)

2.5