In [209]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd

In [371]:
# Load the dataset
df = pd.read_csv('TINPLATE.BO.csv')



In [372]:
df.head()

Date        Open        High         Low       Close   Adj Close  \
0  06-09-2017  168.000000  181.850006  167.000000  174.699997  174.699997   
1  07-09-2017  176.300003  182.000000  173.000000  180.000000  180.000000   
2  08-09-2017  185.050003  190.000000  182.750000  184.449997  184.449997   
3  11-09-2017  186.800003  188.100006  181.850006  184.500000  184.500000   
4  12-09-2017  187.199997  189.449997  184.350006  186.199997  186.199997   

    Volume  
0  1846449  
1   627391  
2   944785  
3   415569  
4   321876

In [217]:
import datetime
x = datetime.datetime.strptime('02-11-2002','%d-%m-%Y').strftime('%d%m%Y')
int(x)

2112002

In [426]:
import datetime
'''df['Date'] = pd.to_datetime(df['Date'])
df['Date']=df['Date'].map(dt.datetime.toordinal)
'''
#df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y') 
#df.head()

x = datetime.datetime.strptime('20-11-2002','%d-%m-%Y').strftime('%d%m%Y')
int(x)

for i in range(0,len(df)):
    df['Date'][i]=int(datetime.datetime.strptime(str(df['Date'][i]),'%d-%m-%Y').strftime('%d%m%Y'))

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':


In [427]:
df.head()

Date        Open        High         Low       Close   Adj Close  \
0   6092017  168.000000  181.850006  167.000000  174.699997  174.699997   
1   7092017  176.300003  182.000000  173.000000  180.000000  180.000000   
2   8092017  185.050003  190.000000  182.750000  184.449997  184.449997   
3  11092017  186.800003  188.100006  181.850006  184.500000  184.500000   
4  12092017  187.199997  189.449997  184.350006  186.199997  186.199997   

    Volume  
0  1846449  
1   627391  
2   944785  
3   415569  
4   321876

In [439]:
#prices_X = df[['Date']]
prices_X = df[['Open','Volume']]

In [440]:
prices_X.shape

(161, 2)

In [441]:
#removing last 20 datapoints
prices_X_train = prices_X[:-10]

In [442]:
prices_X_train.shape

(151, 2)

In [443]:
# last 20 data points
prices_X_test = prices_X[-10:]

In [444]:
df.shape

(161, 7)

In [445]:
prices_y_train = df['Close'][:-10].get_values()

prices_y_test =df['Close'][-10:].get_values()

prices_y_train.shape

(151,)

In [446]:
# creating linear reg obj

regr = linear_model.LinearRegression()

regr.fit(prices_X_train,prices_y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [447]:
prices_y_pred = regr.predict(prices_X_test)

In [448]:
prices_X_test

Open  Volume
151  238.449997  254310
152  242.800003  236610
153  241.500000  356855
154  245.949997  308455
155  248.250000  285423
156  249.100006  454600
157  252.800003  306490
158  241.050003  160326
159  238.600006  149082
160  235.500000  125684

In [415]:
regr.predict(np.array([[235.5,222]]))

array([227.19388525])

In [449]:
prices_X_test_dates = prices_X_test.get_values()

In [450]:
for i in range(0,len(prices_X_test)):
    for j in range(0,len(df)):
        if(prices_X_test_dates[i][0]==df['Open'][j]):
            act_price = df['Close'][j]
        
    print("Open Price: ",prices_X_test_dates[i][0], " Actual_Close: ",act_price," Pred_Close: ",prices_y_pred[i])

Open Price:  238.44999700000002  Actual_Close:  238.5  Pred_Close:  236.62318800970678
Open Price:  242.80000299999998  Actual_Close:  239.19999700000002  Pred_Close:  240.43406186636176
Open Price:  241.5  Actual_Close:  245.649994  Pred_Close:  240.44738377873634
Open Price:  245.94999700000002  Actual_Close:  248.55000299999998  Pred_Close:  244.04222581644316
Open Price:  248.25  Actual_Close:  248.75  Pred_Close:  245.92012129036766
Open Price:  249.100006  Actual_Close:  254.149994  Pred_Close:  248.3951172279074
Open Price:  252.80000299999998  Actual_Close:  242.5  Pred_Close:  250.30292558562442
Open Price:  241.05000299999998  Actual_Close:  237.94999700000002  Pred_Close:  238.0649833048435
Open Price:  238.600006  Actual_Close:  233.5  Pred_Close:  235.706015986294
Open Price:  235.5  Actual_Close:  231.850006  Pred_Close:  232.62927071034906


In [399]:
regr.predict(27052018)

array([24909954.62764214])

In [370]:
prices_X_test_dates

array([[3042018],
       [4042018],
       [5042018],
       [6042018],
       [9042018],
       [10042018],
       [11042018],
       [12042018],
       [13042018],
       [16042018],
       [17042018],
       [18042018],
       [19042018],
       [20042018],
       [23042018],
       [24042018],
       [25042018],
       [26042018],
       [27042018],
       [30042018]], dtype=object)