# NumPy

#### Its Majorly used in AI ML DS

### NumPy Arrays
#### Python Objects:
1) It Contains High level objects: Integer,floationg point

2) Containers: Lists, dictionaries internally build so that We can perform mathamatical operations extensively.

#### NumPy Provides:
1) MultiDimension arrays support <br>
2) Closer to hardware(efficiency) <br>
3) Designed for Sci-fi computations <br>
4) Array oriented computing

In [3]:
import numpy as np

#this creates numpy array from list.
a= np.array([1,2,3]); 

#other way of creating np array
b=np.arange(10);

print(a);

print(b);

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]


#### Why is it useful: Memory Efficient container that provides fast numerical operations

In [21]:
#py lists

li = list(range(1000));

# %timeit here runs the below statement
# 1000 times and calculates the time 
# in terms of mean and std deviation in time
# and gives the time taken to run per loop

%timeit [i**2 for i in li]

382 µs ± 21.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
li = np.arange(1000);
%timeit np.array(i**2 for i in li)

1.88 µs ± 25.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Observation: 
np arrays are almost 200 times faster
that python lists.

In [26]:
# 1-d Array

a = np.array([0,1,2,3,4]);

print(a);

print(type(a));

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [27]:
# prints dimension

print(a.ndim);

1


In [28]:
# Shape

print(a.shape);

(5,)


In [29]:
print(len(a));

5


In [40]:
# 2-D Array

b = np.array([[1,2,3],[4,5,6]]);

print(b);

print("shape is ",b.shape);

print("Length here is no.of rows",len(b));

print("Dimension ",b.ndim);

[[1 2 3]
 [4 5 6]]
shape is  (2, 3)
Length here is no.of rows 2
Dimension  2


In [42]:
# 3-D Array or n-D Array or Tensor

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(c);

print("shape is ",c.shape);

print("Length here is no.of rows",len(c));

print("Dimension ",c.ndim);


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape is  (2, 2, 2)
Length here is no.of rows 2
Dimension  3


# Creating np array using predefined Functions

In [43]:
#arange()

a = np.arange(10);

#start, end, step size
b = np.arange(1,8,2);

print(a,"\n",b);

[0 1 2 3 4 5 6 7 8 9] 
 [1 3 5 7]


In [46]:
# Dividing line into pieces

#start, end, no.of points on line
c = np.linspace(0,1,6)

print(c);

[0.  0.2 0.4 0.6 0.8 1. ]


In [51]:
# one matrix

#3x3 matrix
d = np.ones((3,3))

print(d);

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
# Zero Matrix

e = np.zeros((4,4));

print(e);

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [53]:
# Identity matrix

f = np.eye(3);

print(f);

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
f = np.eye(2,3);

print(f);

[[1. 0. 0.]
 [0. 1. 0.]]


In [55]:
g = np.diag([1,2,3,4]);

print(g);

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [57]:
print(np.diag(g));

[1 2 3 4]


In [61]:
# creating array of rand values

#uniform random number
h = np.random.rand(4);

print(h);

[0.49249107 0.45012952 0.621556   0.2691041 ]


In [62]:
#gaussian random number
i = np.random.randn(4);

print(i);

[-0.95436361  0.99799794  0.03039929  1.47643314]


### Basic Datatypes

In [63]:
a = np.arange(10)

print(a.dtype);

int32


In [78]:
a = np.arange(10, dtype='float')

print(a.dtype);

print(a);

float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [76]:
d = np.array([1+2j,2+4j])

print(d.dtype);

complex128


# Index and Slicing

In [79]:
a = np.arange(6);

print(a[0]);

0


In [80]:
a = np.diag([1,2,3])

print(a[1][1]);

2


In [81]:
a[1,1]=10;

print(a);

[[ 1  0  0]
 [ 0 10  0]
 [ 0  0  3]]


#### Slicing

In [82]:
a = np.arange(10);

print(a[1:6:2]);

[1 3 5]


In [83]:
print(a[2:])


[2 3 4 5 6 7 8 9]


In [84]:
print(a[0:2]);

[0 1]


In [85]:
print(a[:])

[0 1 2 3 4 5 6 7 8 9]


In [86]:
print(a[:3]);

[0 1 2]


In [87]:
print(a[::-1]); #reverse order

[9 8 7 6 5 4 3 2 1 0]


# Memory Sharing

In [88]:
a = np.arange(10);

print(a);

[0 1 2 3 4 5 6 7 8 9]


In [89]:
b = a[::2];

print(b);

[0 2 4 6 8]


In [91]:
print(np.shares_memory(a,b));

True


Observation: Both a and b share same memory i.e b is subset of a it access the elements form a's memory location, internally a view is created from that b will access the values of a.

In [92]:
b[0]=77;

print(b);

print(a);

[77  2  4  6  8]
[77  1  2  3  4  5  6  7  8  9]


Obeseravtion: if we modify 'b', 'a' is also modified because they share memory i.e they are in same location.

# Fancy Indexing
np arrays can be indexed with slices, but also with boolean or integer arrays(masks). This method is called fancy indexing. it creates copies not views.

In [95]:
# it creates 15 rand nums in range 0f 0-20
a = np.random.randint(0,20,15);

print(a);

[ 5 13  0  5 16 13  3  8  7 15  7 12  9  7 10]


In [96]:
mask = (a % 2==0);
print(mask);

[False False  True False  True False False  True False False False  True
 False False  True]


In [98]:
# the index which is true 
# that respective value is printed
print(a[mask]); 

[ 0 16  8 12 10]


Other Example: 

In [103]:
b = np.array([1,2,3,4,5,6,7,8]);

mask = (b % 2 !=0);

b[mask] = -1;

print(b);

[-1  2 -1  4 -1  6 -1  8]


Observation: Replacing all odd indexed values to -1

#### Indexing with an array of integers

In [106]:
a = np.arange(0,100,10);

print(a);

#list of indices, i.e values at this indices
# will be present in the list
print(a[[2,3,2,4,2,5]]);



[ 0 10 20 30 40 50 60 70 80 90]
[20 30 20 40 20 50]


In [109]:
#value at indices 0,3 will be replaced by 77
a[[0,3]]=77;

print(a);

[77 10 20 77 40 50 60 70 80 90]
