# Rand Num Generator(Uniform Distribution)

In [1]:
import random

In [2]:
# generates unifor rand num between 0-1
random.random() 

0.9252182376522041

In [3]:
from sklearn import datasets

iris = datasets.load_iris()

d = iris.data

d.shape

(150, 4)

In [4]:
# converting  numpy array to data frames
import pandas as pd
df = pd.DataFrame(data=d,    # values
              index=range(0,150),    
              columns=['pl','pw','sl','sw']) # 1st row as the column names

Note: above is for my practice

### Creating sample of 30 pts from 150 pts Randomly

In [5]:
n = 150

m = 30

p = m/n

sample = [];

for i in range(0,n):
    if random.random() <= p:
        sample.append(d[i,:])
len(sample) #it might not be exactly 30

29

In [9]:
p,sample

(0.2,
 [array([5.4, 3.9, 1.7, 0.4]),
  array([5. , 3.4, 1.5, 0.2]),
  array([4.8, 3. , 1.4, 0.1]),
  array([5.8, 4. , 1.2, 0.2]),
  array([5.1, 3.5, 1.4, 0.3]),
  array([4.7, 3.2, 1.6, 0.2]),
  array([5.5, 4.2, 1.4, 0.2]),
  array([5.1, 3.8, 1.9, 0.4]),
  array([5. , 3.3, 1.4, 0.2]),
  array([6.4, 3.2, 4.5, 1.5]),
  array([4.9, 2.4, 3.3, 1. ]),
  array([5. , 2. , 3.5, 1. ]),
  array([5.9, 3. , 4.2, 1.5]),
  array([6. , 2.2, 4. , 1. ]),
  array([6.1, 2.9, 4.7, 1.4]),
  array([5.6, 2.9, 3.6, 1.3]),
  array([6.3, 2.5, 4.9, 1.5]),
  array([6.4, 2.9, 4.3, 1.3]),
  array([6.6, 3. , 4.4, 1.4]),
  array([6. , 2.7, 5.1, 1.6]),
  array([7.1, 3. , 5.9, 2.1]),
  array([6.5, 3.2, 5.1, 2. ]),
  array([6.8, 3. , 5.5, 2.1]),
  array([5.7, 2.5, 5. , 2. ]),
  array([7.7, 3.8, 6.7, 2.2]),
  array([6.4, 3.1, 5.5, 1.8]),
  array([6. , 3. , 4.8, 1.8]),
  array([6.3, 2.5, 5. , 1.9]),
  array([5.9, 3. , 5.1, 1.8])])