# Stochastic Gradient Descent(SGD) on Linear Regression on Boston House Prices

In [1]:
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()
boston.data.shape

(506, 13)

In [3]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [4]:
import pandas as pd
bos = pd.DataFrame(boston.data)
bos.head()

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [5]:
# adding Price column to this data set

bos['price'] =boston.target

# considering all cols other than price col
X = bos.drop('price',axis=1)

# Y axis Prices
Y=bos['price']

In [6]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


## Implementing SGD

In [59]:
import numpy as np
x = np.array(x_train)
y = np.array(y_train)
print(x.shape,y.shape)

(354, 13) (354,)


In [116]:

import numpy as np
x = np.array(x_train)
y = np.array(y_train)
w = np.zeros(13)
print(x.shape,y.shape)

(354, 13) (354,)


In [117]:
#w = np.zeros(13)
r=1
li_of_w = []
for i in range(20):
    a = np.matmul(x,w)
    
    b = y - a
    
    
    c = np.matmul(x.T,b)
    
    d = r * c
    #dist = np.linalg.norm(w - (w -d.T))
    w = w -d.T
   
    li_of_w.append(w)


In [118]:
li_of_w

[array([-1.97280104e+04, -1.20113500e+05, -7.93761870e+04, -7.06900000e+02,
        -4.30438327e+03, -5.17462539e+04, -5.22088010e+05, -3.17918210e+04,
        -6.70353000e+04, -3.02210890e+06, -1.45036090e+05, -2.94611687e+06,
        -8.45609230e+04]),
 array([-3.95788840e+12, -8.26388213e+12, -1.00429951e+13, -5.37930902e+10,
        -4.70918010e+11, -5.15290399e+12, -5.93216246e+13, -2.93942306e+12,
        -9.12735047e+12, -3.64219938e+14, -1.54864212e+13, -2.94025404e+14,
        -1.09828941e+13]),
 array([-4.53398557e+20, -8.98435976e+20, -1.12769234e+21, -5.93138004e+18,
        -5.25043141e+19, -5.71895443e+20, -6.62483003e+21, -3.23741836e+20,
        -1.03253072e+21, -4.08531750e+22, -1.72249033e+21, -3.24831332e+22,
        -1.23025168e+21]),
 array([-5.06636778e+28, -9.99861676e+28, -1.25816214e+29, -6.60815849e+26,
        -5.85465392e+27, -6.37481177e+28, -7.38815411e+29, -3.60651734e+28,
        -1.15265955e+29, -4.55760758e+30, -1.92035373e+29, -3.61951642e+30,
       